* Vocabulary                                                            
** deforest [ˌdi:'fɒrɪst]
v. 砍掉（某地）的树林；毁掉（某地）的森林 | 网络 砍伐森林；采伐森林；滥伐森林
** purpose ['pɜrpəs]
n. 目的；用途；目标；意图 | v. 想；决心(做) | 网络 宗旨；效果；意义
** Prot 
网络 第一；蛋白质纤维；原始
** Irreal [ɪ'rɪəl]
网络 不真实的；空虚；非实在的
** garble [ˈɡɑrbəl]
v. 断章取义；无意中歪曲[混淆](事实,意思等)；筛选 | 网络 窜改；错乱；曲解
** interrogating [ɪn'terə.ɡeɪt]
v. 询问；提出问题 | 网络 质问；审问；讯问
** plethora ['pleθərə]
n. 过多；过量；过剩 | 网络 多血症；供过于求；太多
** bewildering [bɪ'wɪldərɪŋ]
adj. 令人困惑的；使人糊涂的 | v. “bewilder”的现在分词 | 网络 令人迷惑的；令人无所适从的；令人眼花缭乱的
** bribe [braɪb]
v. 贿赂；向（某人）行贿 | n. 贿赂 | 网络 收买；向...行贿；买通
** bully ['bʊli]
v. 恐吓；胁迫；伤害 | adj. 顶好的；快活的；盛气凌人的 | n. 仗势欺人者；横行霸道者 | int. 好 | 网络 欺负；霸凌；欺凌
** defences [dɪ'fensɪs]
n. 防御；保护；辩护；【法】(被告的)抗辩 | 网络 防卫；防御设备；心灵防御机制
** gazillion [ɡə'zɪljən]
n. 很大的数目 | 网络 许许多多；兆亿；亿万的
** capitalism ['kæpɪt(ə)l.ɪzəm]
n. 资本主义 | 网络 现代资本主义；资本制度；资本主义这个词
** surveillance [sər'veɪləns]
n. （对犯罪嫌疑人或可能发生犯罪的地方的）监视 | 网络 监督；监控；监测
** malleable ['mæliəb(ə)l]
adj. 可锻造的；可轧压的；易成型的；可塑的 | 网络 有延展性的；可锻的；韧性的
** outspoken [aʊt'spoʊkən]
adj. 直率的 | v. “outspeak”的过去分词 | 网络 坦率的；直言的；坦率直言的
** propped [prɑp]
n. 支柱；道具；支撑物；支持者 | v. 支撑 | 网络 螺旋桨；斜撑式
** monad ['mɒnæd]
n. 单子（不可分割的实体） | 网络 单分体；一价物；单孢体
** on-the-fly 
na. 〈非正式〉匆匆忙忙地；在空中；飞行中；【计】(计算机)运行中 | 网络 装头在高速移动中；即时；高速数据传输错误纠正
** enumerate [ɪ'numə.reɪt]
v. 枚举；列举 | 网络 计算；数；历数
** imperative [ɪm'perətɪv]
adj. 重要紧急的；迫切的；急需处理的；表示权威的 | n. 重要紧急的事；必要的事；祈使语气；祈使语气动词 | 网络 命令式；强制的；祈使句
** eliminate [ɪˈlɪməˌnet]
v. 消除；消灭；清除；淘汰 | 网络 排除；除去；剔除
** 一致性 
n. compliance; compatibility | 网络 consistency; consistent; uniformity
** interloper ['ɪntər.loʊpər]
n. 闯入者；干涉者 | 网络 干涉他人事务者；无执照营业者；不请自来者
** interstate ['ɪntər.steɪt]
adj. 州际的 | n. （美国）州际公路 | 网络 各州之间；洲际公路；洲际的
** countenance ['kaʊntənəns]
n. 面容；脸色；面部表情 | v. 支持；赞成；同意 | 网络 容貌；嘴脸
** bespectacled [bɪ'spektək(ə)ld]
adj. 戴眼镜的 | 网络 带眼镜的；有戴眼镜的；眼镜娘
** outpost ['aʊt.poʊst]
n. 前哨（基地）；偏远村镇；孤零住区 | 网络 前哨站；前哨基地；哨所
** cultish 
网络 狂热的；膜拜仪式的；异教规条
** ecstatic [ɪk'stætɪk]
adj. 狂喜的；热情极高的 | 网络 欣喜若狂的；入迷的；狂喜的人
** euphoria [ju'fɔriə]
n. （通常指持续时间较短的）极度愉快的心情 | 网络 欣快；欣快感；欣快症
** engross [ɪn'ɡroʊs]
v. 使全神贯注；占去（某人的）全部注意力和时间 | 网络 全神贯注于；吸引；占用
** candidly ['kændidli]
adv. 坦白地 | 网络 率直地；坦率地；率直坦白地
** renegade ['ren.ɪɡeɪd]
n. 叛徒；叛逆者；背叛者；变节者 | v. 变节；脱党；背教 | adj. 变节的 | 网络 叛教者；变节点数
** niches [nɪtʃ]
n. 壁龛；(适合个人性格,能力等的)适当地位；【生】小生境；【地】雪凹 | 网络 利基；生态位；利基市场
** inconsistency [.ɪnkən'sɪstənsi]
na. “inconsistence”的变体 | 网络 矛盾；不一致；不一致性
** constituent [kən'stɪtʃuənt]
n. 成分；构成要素；（选区的）选民 | adj. 组成的；构成的 | 网络 形成的；组分；成份
** predicate ['predɪkeɪt] 
v. 断言；使基于；使以…为依据；表明 | adj. 述语的；谓项的 | n. 谓语（句子成分，对主语加以陈述，如 John went home 中的 went home） | 网络 谓词；述词；断定
** Lexical ['leksɪk(ə)l]
adj. 词汇的 | 网络 词法；词法的；辞典的
** derivative [dɪ'rɪvətɪv]
n. 衍生物；派生词；衍生字；派生物 | adj. 模仿他人的；缺乏独创性的 | 网络 导数；派生的；衍生工具
** elucidate [iˈluːsiˌdeɪt]
v. 说明；解释；阐明；阐释 | 网络 阐发；的阐明；阐明并发挥
** 规约 [guī yuē] 
na. stipulations of an agreement | 网络 protocol; Specification; Statute
** mediocre [.midi'oʊkər]
adj. 平庸的；普通的；平常的 | 网络 普普通通的；中等的；平凡的
** concatenation [kən.kætə'neɪʃ(ə)n]
n. 一系列相关联的事物（或事件） | 网络 串联；连接；串接
** circumscribe ['sɜrkəm.skraɪb]
v. 限制；画…的外接圆 | 网络 在...周围画线；约束；外切
