* Linux输入子系统（input subsystem）对JingOs交互模式的发展性探讨
** 什么是输入子系统（input subsystem）
   - 输入子系统是Linux系统和各种驱动（device driver）联系的接口
   - 最简单的案例是当键盘按下（press）时，便会以当前的时间
     （gettimeofday），精确到微秒，向系统发送一个事件（event），然后系
     统会等待下一个事件，或许是另一个按键，也或许是当前按键的释放
     （release）事件。
   - 事件的发送方式是向设备驱动的device写入相应数据结构的数据，这里使
     用的struct event。
** 头文件
   - 输入子系统的头文件是<linux/input.h>
     1. event结构体的定义，包含各种事件类型（type），事件代码（code），
        与事件状态（value）
     2. define各种BUS类型的ID，MT_TOOL（这个我不清楚是什么东西）
     3. input_id结构体的定义，包含设备驱动的各种信息
     4. 以及各种获取信息的宏定义
     5. 还有其他的一些结构体，因为我没有使用场景，在此就不加赘述
   - 还有一个头文件是<linux/input-event-codes.h>
     1. 内部包含键盘上面各种字母和符号分别对应的事件代码（code）
     2. 不同的Linux内核版本对此头文件进行扩展即可添加新的键盘事件，有
        利于模块化管理
** 应用
   - 最简单的应用便是手动的向设备对应的文件写入响应的数据来模拟各种事
     件的发生
   - 当然前提是程序拥有/dev/input/event文件的写入权限，因为直接获取底
     层的文件写入权限在系统方面是十分危险的操作
   - 其他的应用则是建立在普通的应用的基础上，进行的各种变换，例如建立
     一个代理，将一个键盘事件映射到另外一个事件上，有不少的键盘映射是
     建立在输入子系统的编程上面
** 为什么JingOs需要支持键盘事件的增益
   - 这里说的增益是，在触屏事件的支持下，完成触屏事件对键盘事件进行映
     射，进而补充或完善用户的体验，甚至是减少不兼容事件
   - 因为当前JingOs，是简单粗暴的将原来的应用软件的缩放，关闭三个按钮
     给杀掉，然后再将所有的应用都通过三个手势进行管理，虽然是为了对标
     苹果的平板而推出的基于kde手势操作进行的系统。
** 窗口管理器快捷键--Linux各种发行版的宝藏，连接WM和系统的桥梁
   - 虽然手势看起来是非常高明的操作，但就我拙见，还是不够明了，尤其是
     对于键盘党和新用户而言，杀掉一个应用由原来的只需要点击右上角的关
     闭按钮变成先移动鼠标到界面边缘，再进行进程管理。对于没有使用过
     Linux发行版的人一下子也很难想到将鼠标划到边缘
   - 而实际上，KDE是有他本身的杀掉进程的方式的，便是向窗口管理器（aka
     wm）发送一个alt-f4键盘事件，缩小也可以进行快捷键的设置。缩小也是
     同理，对于很多窗口管理器只要按下win-d就可以隐藏所有应用，尽管并没
     有任何动画，但是十分的方便快捷
   - 甚至是切换应用，也仅仅只是简单的发送一个alt-tab键盘事件而已，尽管
     经过简单的逻辑思考后，我们便可以知道这种方式只能在两个程序之间进
     行来回切换，就像安卓那样，连点两次那个方块便会返回上一个应用，再
     次双击，则又返回原来的应用。既然他实现不了整个窗口序列的循环，那
     在这里为什么要提他呢？此处卖一个关子
   - 除此以外还有左右分屏功能，也因为简单粗暴的窗口管理方式，变得没有
     入口，尽管KDE支持这个功能，目前因为也是没有用过JingPad，没有办法
     进行一个上手体验，无法进行评价
   - 由此我们已经很简单的确定了原来安卓的三大金刚键的原理，由此便可以
     简单的做出JingOs的三大金刚键。尽管我本身并没有开发GUI程序的经验，
     但是经过简单推断，肯定可以开发出一个控件，他可以接受鼠标点击，也
     可以接受触屏事件，然后触发一个动作，但是并不改变鼠标和键盘的焦点，
     他可以时时刻刻位于所有应用程序的显示之上，同时他又可以降低透明度
     来减少用户视野被阻碍导致的不适感觉。
   - 对于GUI开发的人员一定有办法可以实现这种控件，因为我们可以找到一个
     应用已经拥有了这些特性，那就是输入法显示的那个框框。
** 应用快捷键--提高效率的不二之选
   - 众所周知，Linux软件（此处专指带GUI的），并不会专门的提供返回前进
     功能，除了各个浏览器（提供历史记录的前进与后退）与系统软件（指
     gnome或者kde等的系统设置等软件），他们会提供ESC退出小窗口。但是这
     些无伤大雅，用户只消使用一段时间便会发现这些与电脑上的逻辑是相同的。
   - 作为重度但又不是那么深度的快捷键使用者，emacs作为我平时bash和c的
     编辑器，以及markdown与org文档的编辑器，快捷键对于我来说是完全离不
     开的东西，每敲几行东西就会手动的保存一些东西，然后思考接下来要怎
     么做，这些都是成为自然的动作。在浏览器中我也会使用ctrl-t创建新标
     签，使用ctrl-w关闭一个标签
   - 题外话：作为输入效率的追求者，很多人都是一入五笔深似海，一入双拼
     深似海。这点我相信在系统使用上也是适用的。
   - 至少我个人感觉比鼠标点击快很多，虽然鼠标在选取一些精确控件的作用
     也是极其突出，而我平时使用触摸板也是和鼠标差不多。
   - 快捷键在各个IDE中也是不可或缺的，尽管我平时是使用emacs进行c的编程，
     但是在WEB编程中，个人还是觉得vscode和webstorm更合适一些。虽然我使
     用的很少(前者因为各种配置眼花缭乱，后者是因为我的电脑运行起来有些
     吃力)，但他们也会提供快捷键的支持。
** JingOs上的快捷键，及其起源
   - 这是在JingOs上运行传统桌面程序与所谓安卓平板应用还有ipad平板上应
     用最大的不同。因为除JingPad有原生电脑生态，其他的平板上运行的大多
     是针对触屏事件进行优化好的各个触屏控件组织起来的应用程序，他们有
     各自的开发套件
   - 而JingOs上的应用目前来说几乎都没有对触屏事件进行适配，开发所用的
     据我所知，或为electron，或为qt，或为GTK应用。快捷键这一功能，可以
     说是天生与JingOs相贴合的。我在虚拟机上看过JingOs x86版本上的一些
     应用，那些没有提供对键盘的支持，可能是因为实现的功能不需要太多的
     操作，或是处于出于对触屏软件开发的经验积累，这些应用都采用卡片式
     的布局，实现它们自己的功能，这种方式确实是能够降低软件构建难度
   - 但是如果对于将来其他软件厂商是否要进行这种平板模式应用的开发，以
     及如何降低这些软件的适配程度，这其实是一个值得考量的问题，例如是
     否要专门的削减掉菜单（menu）功能，进行软件布局的重构，这是一个小
     问题，关于如何降低其他软件厂商对JingOs的适配成本，因为这些软件其
     本质还是Linux桌面应用程序，只不过是进行布局重构。就其开发模式而言，
     是使用QT widget进行开发，还是重新使用QT quick进行开发，就其成本，
     因为我本身没有太多的GUI开发经验，所以在此留一个小疑惑。
** 从触屏操作到快捷键高级操作
   - 是的，我们现在已经拥有了所有的功能，只要经过精心的设计，我们便可
     以为用户提供一个迈向新世界的路子，从触屏到键盘模拟再到快捷键的使
     用，几乎可以不损耗任何性能，即可快捷的为用户打开各种功能的传送门
   - 为什么一定是快捷键，快捷键作为桌面系统与系统沟通的桥梁，他能增强
     用户对于复杂系统的体验。Windows作为一个系统，我使用它作为系统用了
     一年多，后来我学习了转到Linux，之后又兜兜转转，完全放弃了Windows。
   - 因为Windows不能为我实现一个简简单单的快捷键启动浏览器的功能，也不
     能为我快速启动我的emacs。也不能为我启动我的终端，而终端又是另外一
     个神秘接口了。
   - 到了这里前面提到的两个窗口不断循环的问题了，快捷键本身就是告诉操
     作系统或者应用：到时候了，你可以运行一个特定的程序了，那么这个程
     序有什么限制吗？几乎没有！！！
   - 如果你会编写一个shell脚本，利用Linux众多开源软件的帮助下，你就可
     以解决上述的问题，wmctrl是一个可以操作软件窗口的应用，是的，他是
     一个shell程序，我们可以利用它来快速选取我们想要的程序到我们桌面最
     前端
     #+BEGIN_SRC bash
     wmctrl -a "emacs"
     #+END_SRC
   - Just run like this, 就像这样运行，你就可以快速的将你的某个程序提
     到你的面前，这种效率的提升是巨大的，而且简单明了，可以让人体会到
     Linux的魅力
** 为什么一定是快捷键（此处可能有强烈的主观成分
   - 在前面我简单的提到了这一点，但是觉得还是需要再次提一句
   - 在网上我看到很多人提到mac键盘多么多么好用，经过考虑后我觉得是与
     macos对快捷键的管理是分不开的，可惜我也没钱买Mac，所以此处可能具
     有强烈的主观猜测成分
   - 如果对标ipad的手势操作，那么我们为什么不把快捷键也推广给用户呢？
     每个mac都会有一张他们的快捷键表，其实可能就是为了提高用户的粘性，
     用习惯了就很难改变了，Linux是有这种潜力的。我现在本人使用的是
     Ubuntu桌面环境，前些日子也是尝鲜装了一下gnome40,发现不舒服，还是
     老老实实使用我的Ubuntu了，对于kde我个人也是用的不是很习惯
   - 但是我并没有直接的数据来进行有力的论证，因为我本身对于快捷键的拥
     护和极有可能导致在付出极大的热情之后，我做出来一个不能符合用户需
     求的东西，毕竟我代表不了所有用户。
   - 因此此处是可能带有强烈的主观意思在里面的，出于谨慎的态度，我不得
     不承认这一点的存在，甚至整篇文章都是有强烈的主观色彩在其中的，目
     的也可能是为了让你们觉得我这篇文章是有价值的，在此这一点必须进行
     声明，我需要承认自己的思维不是完美的。但不完美也可以有其自己的价值
** 为什么选择Linux输入子系统作为用户触屏和键盘输入的媒介
   - Linux输入子系统在这里起到的是承上启下的作用，因为当前wayland对整
     个window compositor进行了新的重构，目的是加强整个系统的安全与减少
     系统的体量，其禁止了其他的程序直接获取本程序的各种事件。
   - 或许存在某种方式可以采用传递的方法，通过一个软件进行键盘事件的传
     递，这点或许是可行的，但我个人觉得有些繁琐，当前是超出了我的个人
     能力范围之外。
   - 而直接使用Linux输入子系统就可以忽视掉window compositor产生的影响，
     越过软件层，直接获取键盘输入信息，但是又可能会出现隐藏的安全问题
   - 综上，选择Linux子系统是出于降低系统复杂度的角度考虑的，目前证明是
     可行的方案
** 键盘宏
   - 我这些日子写完键盘宏的小程序后，在github上面也发现了同样类型的
     [[https://github.com/snyball/Hawck][hawck-a key-rebinding daemon]]， 也是基于Linux输入子系统的具有键盘宏录制
     功能的软件，我看了一下，确实是相形见绌，我的代码能力确实是需要进步
   - 键盘宏是指两个及两个以上键盘事件，因为有些快捷键是需要一个前缀
     （prefix）快捷键的， 如emacs如果要保存一个文件，就要输入ctrl-x、
     ctrl-s才能进行文件的保存，emacs还有三个键盘事件的响应，只是我一般
     不用，在此就不加赘述。
   - 那么为什么还要进行实时的录制与播放，主要是为了考虑到有些时候键盘
     的相应不是实时的，用户在使用时可能出现一些bug，因此在录制的时候也
     加入了时间轴录制，以便更好适应用户的应用场景
** 这种交互模式发展的内在组织动力--关于复杂自适应系统
   - 根据复杂自适应系统的特征，复杂性是具有及时进化潜能的个体群宏观集
     体行为的研究
   - 它们的交互性为导致了一致的集体现象，这种突变属性只能在比那些单个
     的个体更高的层次上进行描述。
   - 于是，在已有良好键盘支持的情景之下，引入触屏事件会导致交互方式发
     生变化，尤其是在Linux这种高度可定制化的系统之上，新的交互方式总会
     随着时间迁移进行新的“突变”或者称之为“聚合”，将为系统带来新的
     特性
   - 而这种突变就是交互模式发展的内在组织动力，是系统自适应产生的结果
** 总结
   - 合理的引入触屏事件触发键盘事件是可以增强用户的使用体验的，这点作
     为我的主观感受、主观论断，或许需要更加详细的调查进行数据支持，但
     是这是我能想到的目前可以快速提升用户体验的方法了
   - 举个例子，在无键盘使用终端的情况时，用户使用搜狗虚拟键盘输入一个
     命令，他是没有办法来使用ctrl-c来终止一个程序的运行的，这点在我看
     来是致命的
   - Linux桌面环境下用户面临的各种情景是复杂的，信息流，事件流复杂多变，
     信息密度是极高的。每个控件或许都有他自己独特的功能，这是以往安卓
     平板和苹果平板不能比拟的。用户会自然而然的选取效率更高，更方便的
     方式来进行各种操作
   - 在合理的引入这种机制以后，可以完善虚拟键盘的体验，我们到后面或许
     也可以为用户省去一个键盘的价钱！！！
   - 更重要的是，通过这种方式。我们可以利用已有的系统（快捷键系统、键
     盘输入系统、触屏系统），快速构建起一个用户到系统的接口，而不会破
     坏任何系统自有的属性。给（jǐ）予用户自由（free）操作的权力。这本
     身是与Linux的理念相切合的
   - 但是因为用户本身的水平参差不齐，很少有用户能够自己赋予自己这种权
     力，于是就需要官方来引导、管理整个交互系统软件的构建，由官方减少
     用户使用的阻力，以及建立强大的生态系统
   - 而且这是与其他的软件提供商进行交流的一个好机会，用于生态的建立，
     或许可能建立一个小小的快捷键标准来降低厂商的适配成本，毕竟做好一
     个系统最终还是需要整个行业的支持才能走的更远，缺少协作与沟通最终
     的产出只能是一个自娱自乐的工具，，而这正是共享与协作存在的意义所在
